# Generated by Django 5.1.6 on 2026-02-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_vector', models.JSONField()),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_features_model', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Image Features',
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('day1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day4_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day5_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day6_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day7_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendation', models.CharField(choices=[('best_price', '🟢 Best Price'), ('wait', '🟡 Wait - Price Drop Likely'), ('neutral', '⚪ Neutral')], default='neutral', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='products.product')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='TFIDFIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_tags', models.JSONField(default=list)),
                ('tfidf_scores', models.JSONField(default=dict)),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tfidf_index', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'TFIDF Indices',
            },
        ),
    ]
