# Generated by Django 5.1.6 on 2026-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceprediction',
            name='price_change',
            field=models.FloatField(default=0.0, help_text='Percentage change in price'),
        ),
    ]
