# Generated by Django 5.1.6 on 2026-02-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('active_users_count', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trending_products', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('searches_count', models.IntegerField()),
                ('purchase_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_records', to='products.product')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['-timestamp', 'rank'], name='site_analyt_timesta_43b8c9_idx')],
            },
        ),
    ]
