# Generated by Django 5.1.6 on 2026-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_agegroup_ecotag_gendercategory_occasion_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
