# Generated by Django 5.1.6 on 2026-09-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('net_banking', 'Net Banking')], default='cash', max_length=20),
        ),
    ]
